tiendamfej/catalogos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('clientes/', views.homeCliente, name='homeCliente'),
    path('clientes/ver/<int:cliente_id>/', views.verCliente, name='verCliente'),
    path('clientes/actualizar/<int:cliente_id>/', views.actualizarCliente, name='actualizarCliente'),
    path('clientes/borrar/<int:cliente_id>/', views.borrarCliente, name='borrarCliente'),
    path('clientes/crear/', views.crearCliente, name='crearCliente'), 
    
    path('producto', views.homeProducto, name='homeProducto'),
    path('producto/<int:id>/', views.verProducto, name='verProducto'),
    path('producto/nuevo/', views.crearProducto, name='crearProducto'),
    path('producto/actualizar/<int:id>/', views.actualizarProducto, name='actualizarProducto'),
    path('producto/eliminar/<int:id>/', views.borrarProducto, name='borrarProducto'),
]

tiendamfej/generales/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home , name='home'), 
]

tiendamfej/tiendamfej/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generales.urls')),
    path('catalogos/', include('catalogos.urls')),
    
    
    #path('registro/', include('usuarios.urls', namespace='registro')),  
    #path('login/', include('usuarios.urls', namespace='login')),
    #path('logout/', include('usuarios.urls', namespace='logout')),
    #path('', lambda request: redirect('usuarios:login')),
]

tiendamfej/usuarios/urls.py
from django.urls import path
from .views import login, registro, logout

app_name = 'usuarios' 

urlpatterns = [
    path('login/', login, name='login'), 
    path('registro/', registro, name='registro'),
    path('logout/', logout, name='logout'),
]

tiendamfej/catalogos/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=150)
    telefono = models.CharField(max_length=15)
    rfc = models.CharField(max_length=13)
    direccion = models.TextField()
    correo_electronico = models.EmailField()

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"
    
class Producto(models.Model):
    producto = models.CharField(max_length=100)
    categoria = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()

    def __str__(self):
        return self.producto

tiendamfej/facturas/models.py
from django.db import models

# Create your models here.

tiendamfej/generales/models.py
from django.db import models

# Create your models here.

tiendamfej/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    # Añade related_name únicos para evitar conflictos
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_groups',  
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_permissions',  
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

tiendamfej/catalogos/forms.py
from django import forms
from .models import Cliente, Producto

class clienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellidos', 'telefono', 'rfc', 'direccion', 'correo_electronico']
        

class productoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['producto', 'categoria', 'precio', 'descripcion']

tiendamfej/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

tiendamfej/catalogos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cliente, Producto
from .forms import clienteForm, productoForm

# Create your views here.

#CLIENTES
def homeCliente(request):
    clientes = Cliente.objects.all()
    return render(request, 'homeCliente.html', {'clientes': clientes})

def verCliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    return render(request, 'verCliente.html', {'cliente': cliente})

def actualizarCliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = clienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('homeCliente')
    else:
        form = clienteForm(instance=cliente)
    return render(request, 'actualizarCliente.html', {'form': form})

def borrarCliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        cliente.delete()
        return redirect('homeCliente')
    return render(request, 'borrarCliente.html', {'cliente': cliente})

def crearCliente(request):
    if request.method == 'POST':
        form = clienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homeCliente')
    else:
        form = clienteForm()
    return render(request, 'crearCliente.html', {'form': form})


#PRODUCTOS
def homeProducto(request):
    productos = Producto.objects.all()
    return render(request, 'homeProducto.html', {'productos': productos})

# Ver detalles de un producto
def verProducto(request, id):
    producto = get_object_or_404(Producto, id=id)
    return render(request, 'verProducto.html', {'producto': producto})

# Crear un nuevo producto
def crearProducto(request):
    if request.method == 'POST':
        form = productoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homeProducto')
    else:
        form = productoForm()
    return render(request, 'crearProducto.html', {'form': form})

def actualizarProducto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == 'POST':
        form = productoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('homeProducto')
    else:
        form = productoForm(instance=producto)
    return render(request, 'actualizarProducto.html', {'form': form})

# Borrar un producto
def borrarProducto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == 'POST':
        producto.delete()
        return redirect('homeProducto')
    return render(request, 'borrarProducto.html', {'producto': producto})

tiendamfej/facturas/views.py
from django.shortcuts import render

# Create your views here.

tiendamfej/generales/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

tiendamfej/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm
from django.contrib import messages

# Create your views here.
def login(request):
    if request.method == 'POST':
        email = request.POST['email']  
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)  
        if user is not None:
            login(request, user)
            return redirect('inicio') 
        else:
            return render(request, 'login.html', {'error': 'Credenciales incorrectas'})
    return render(request, 'login.html')

def logout(request):
    logout(request)
    return redirect('login')

def registro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Tu cuenta ha sido creada exitosamente.')
            return redirect('usuarios:login.html') 
        else:
            print(form)
    else:
        form = CustomUserCreationForm()
    return render(request, 'registro.html', {'form': form})

tiendamfej/catalogos/templates/actualizarCliente.html
<style>
    .btn-group {
        display: flex;         
        gap: 10px;          
        margin-top: 15px;      
    }
</style>

{% extends "base.html" %}

{% block title %}Actualizar Cliente{% endblock %}

{% block content %}
<div class="container">
    <h2>Actualizar Cliente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="btn-group">
            <button type="submit" class="btn btn-success">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Guardar cambios</span>
            </button>

            <a href="{% url 'homeCliente' %}" class="btn btn-primary">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
        </div>
    </form> 
{% endblock %}

tiendamfej/catalogos/templates/actualizarProducto.html
<style>
    .btn-group {
        display: flex;         
        gap: 10px;          
        margin-top: 15px;      
    }
</style>

{% extends "base.html" %}

{% block title %}Actualizar Producto{% endblock %}

{% block content %}
<div class="container">
    <h2>Actualizar producto</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <div class="btn-group">
            <button type="submit" class="btn btn-success">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Guardar cambios</span>
            </button>

            <a href="{% url 'homeCliente' %}" class="btn btn-primary">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
        </div>
    </form>
</div>
{% endblock %}

tiendamfej/catalogos/templates/borrarCliente.html
{% extends "base.html" %}

{% block title %}Borrar Cliente{% endblock %}

{% block content %}
<div class="card shadow mb-4 text-center">
    <div class="ard-header py-3">
        <h2>¿Estás seguro de que deseas borrar a {{ cliente.nombre }} {{ cliente.apellidos }}?</h2>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                <span class="icon text-white-50">
                    <i class="fas fa-trash"></i>
                </span>
                <span class="text">Borrar cliente</span>
            </button>
            <a href="{% url 'homeCliente' %}" class="btn btn-primary">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
        </form>
    </div>
</div>
{% endblock %}

tiendamfej/catalogos/templates/borrarProducto.html
{% extends "base.html" %}

{% block title %}Eliminar Producto{% endblock %}

{% block content %}
<div class="card shadow mb-4 text-center">
    <div class="ard-header py-3">
        <h2>¿Estás seguro de que deseas eliminar el producto "{{ producto.producto }}"?</h2>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
                <span class="icon text-white-50">
                    <i class="fas fa-trash"></i>
                </span>
                <span class="text">Borrar producto</span>
            </button>
            <a href="{% url 'homeProducto' %}" class="btn btn-secondary">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
</div>
{% endblock %}

tiendamfej/catalogos/templates/crearCliente.html
<style>
    .btn-group {
        display: flex;         
        gap: 10px;          
        margin-top: 15px;      
    }
</style>

{% extends "base.html" %}

{% block title %}Agregar Cliente{% endblock %}

{% block content %}
<div class="container">
    <h2>Agregar Cliente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <div class="btn-group">
            <button type="submit" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Guardar registro</span>
            </button>
    
            <a href="{% url 'homeCliente' %}" class="btn btn-secondary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
        </div>
    </form>

{% endblock %}

tiendamfej/catalogos/templates/crearProducto.html
<style>
    .btn-group {
        display: flex;         
        gap: 10px;          
        margin-top: 15px;      
    }
</style>

{% extends "base.html" %}

{% block title %}Agregar Producto{% endblock %}

{% block content %}
<div class="container">
    <h2>Agregar Producto</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="btn-group">
            <button type="submit" class="btn btn-primary">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Guardar registro</span>
            </button>

            <a href="{% url 'homeProducto' %}" class="btn btn-secondary">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Cancelar y volver</span>
            </a>
        </div>
    </form>
</div>
{% endblock %}

tiendamfej/catalogos/templates/homeCliente.html
{% extends "base.html" %}

{% block title %}Home Clientes{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Clientes </h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista de clientes
                <a href="{% url 'crearCliente' %}" class="btn btn-primary float-right">Agregar Cliente</a>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr style="text-align: center;">
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th>Teléfono</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cliente in clientes %}
                        <tr style="text-align: center;">
                            <td>{{ cliente.nombre }}</td>
                            <td>{{ cliente.apellidos }}</td>
                            <td>{{ cliente.telefono }}</td>
                            <td>
                                <a href="{% url 'verCliente' cliente.id %}" class="btn btn-info btn-sm">Ver</a> 
                                <a href="{% url 'actualizarCliente' cliente.id %}" class="btn btn-info btn-sm">Actualizar</a> 
                                <a href="{% url 'borrarCliente' cliente.id %}" class="btn btn-info btn-sm">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tiendamfej/catalogos/templates/homeProducto.html
{% extends "base.html" %}

{% block title %}Home productos{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Productos </h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista de productos
                <a href="{% url 'crearProducto' %}" class="btn btn-primary float-right">Agregar Producto</a>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr style="text-align: center;">
                            <th>Producto</th>
                            <th>Categoria</th>
                            <th>Precio</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                        <tr style="text-align: center;">
                            <td>{{ producto.producto }}</td>
                            <td>{{ producto.categoria }}</td>
                            <td>{{ producto.precio }}</td>
                            <td>
                                <a href="{% url 'verProducto' producto.id %}" class="btn btn-info btn-sm">Ver</a> 
                                <a href="{% url 'actualizarProducto' producto.id %}" class="btn btn-info btn-sm">Actualizar</a> 
                                <a href="{% url 'borrarProducto' producto.id %}" class="btn btn-info btn-sm">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tiendamfej/catalogos/templates/verCliente.html
{% extends "base.html" %}

{% block title %}Detalles del Cliente{% endblock %}

{% block content %}
<div class="container">
    <h2>Detalles del Cliente</h2>
    <p><strong>Nombre:</strong> {{ cliente.nombre }}</p>
    <p><strong>Apellidos:</strong> {{ cliente.apellidos }}</p>
    <p><strong>Teléfono:</strong> {{ cliente.telefono }}</p>
    <p><strong>RFC:</strong> {{ cliente.rfc }}</p>
    <p><strong>Dirección:</strong> {{ cliente.direccion }}</p>
    <p><strong>Correo Electrónico:</strong> {{ cliente.correo_electronico }}</p>
    <a href="{% url 'homeCliente' %}" class="btn btn-primary">
        <span class="icon text-white-50">
            <i class="fas fa-arrow-left"></i>
        </span>
        <span class="text">Regresar</span>
    </a>
</div>
{% endblock %}

tiendamfej/catalogos/templates/verProducto.html
{% extends "base.html" %}

{% block title %}Ver Producto{% endblock %}

{% block content %}
<div class="container">
    <h2>Detalles del Producto</h2>
    <p>Producto: {{ producto.producto }}</p>
    <p>Categoria: {{ producto.categoria }}</p>
    <p>Precio: {{ producto.precio }}</p>
    <p>Descripción: {{ producto.descripcion }}</p>
    <a href="{% url 'homeProducto' %}" class="btn btn-secondary">
        <span class="icon text-white-50">
            <i class="fas fa-arrow-left"></i>
        </span>
        <span class="text">Regresar</span>
    </a>
</div>
{% endblock %}

tiendamfej/usuarios/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Login{% endblock %}</title>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block" 
                                style="background-image: url('{% static 'img/facturalogo.png' %}'); 
                                background-size: cover;
                                background-position: center;
                                background-repeat: no-repeat;"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                                    </div>
                                    <form method="POST" class="user">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" name="email" placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="password" placeholder="Password">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'usuarios:registro' %}">Crea una cuenta aquí</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{%static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{%static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{%static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{%static 'js/sb-admin-2.min.js' %}"></script>

</body>
</html>

tiendamfej/usuarios/templates/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Crear cuenta{% endblock %}</title>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    <div class="container">
        {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-7 d-none d-lg-block" 
                        style="background-image: url('{% static 'img/facturalogo.png' %}'); 
                        background-size: cover;
                        background-position: center;
                        background-repeat: no-repeat;"></div>
                    <div class="col-lg-5">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Crear cuenta</h1>
                            </div>
                            <form method="POST" action="{% url 'usuarios:registro' %}" class="user">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" name="first_name" class="form-control form-control-user" placeholder="First Name" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" name="last_name" class="form-control form-control-user" placeholder="Last Name" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" class="form-control form-control-user" placeholder="Email Address" required>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" name="password1" class="form-control form-control-user" placeholder="Password" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" name="password2" class="form-control form-control-user" placeholder="Repeat Password" required>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary btn-user btn-block">Registrar cuenta</button>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'usuarios:login' %}">¿Ya tienes una contraseña? Ingresa aquí</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if errors %}
    <div class="alert alert-danger">
        {% for error in errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>
</html>